### ISSUE TITLE
Version 3.0.0: Incoming AMC data is not getting processed

### ISSUE THREAD

**Issue by davidbeckonline** [aws-solutions/amazon-marketing-cloud-insights-on-aws#10]
**Describe the bug**
After the upgrade from version 2.0.3 to version 3.0.0 new data coming from AMC is not getting processed in the data lake anymore.

**To Reproduce**
We have been able to reproduce this issue in an update scenario (from v2.0.3) and a completely new (test) implementation.
In both cases, the S3 output bucket for AMC already existed. We did not create a new bucket as part of the TPS.

**Expected behavior**
When new API request based data arrives in the AMC output bucket (which was defined as part of the TPS), then we would expect the solution to pick up the new file and process it:
1. copy to `pre-stage`
2. transform to parquet and store in `post-stage`

**Additional Info**
We checked the `*-sm-a' StateMachine in the StepFunctions. Even though multiple new AMC files arrived in the AMC output S3 bucket, this StateMachine was not executed. For the upgrade scenario, we see that the execution stopped on the day of the upgrade.

**Please complete the following information about the solution:**
- [ ] Version: [v3.0.0]
- [us-east-1] Region
- [ NO ] Was the solution modified from the version published on this repository?
- [ N/A ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ YES ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ NO ] Were there any errors in the CloudWatch Logs

**Comment by andrewmarriott-aws** [comment]
Following up to confirm this has been fixed with the release of [v3.1.0](https://github.com/aws-solutions/amazon-marketing-cloud-insights-on-aws/releases/tag/v3.1.0)

Closing this thread as resolved
